id = "nesfab"
name = "NESFab"
description = "NESFab support."
version = "0.1.0"
schema_version = 1
authors = ["hnd2"]
repository = "https://github.com/hnd2/zed-nesfab"

[language_servers.nesfab]
name = "NESFab Language Server"
language = "NESFab"

[grammars.nesfab]
repository = "https://github.com/hnd2/tree-sitter-nesfab"
commit = "7e1fadd17e2fa86b0cff23e234b5e92891ebdd70"
