id = "nesfab"
name = "NESFab"
description = "NESFab support"
version = "0.1.0"
schema_version = 1
authors = ["hnd2 <hnd@example.com>"]
repository = "https://github.com/hnd2/zed-nesfab"

[language_servers.nesfab]
name = "NESFab LSP"
language = "NESFab"

[grammars.nesfab]
repository = "https://github.com/hnd2/tree-sitter-nesfab"
commit = "2b63c243bbc0c6cebf6e8b125d2c7b7423c6eb61"
