id = "nesfab"
name = "NESFab"
description = "NESFab support"
version = "0.1.0"
schema_version = 1
authors = ["hnd2 <hnd@example.com>"]
repository = "https://github.com/hnd2/zed-nesfab"

[language_servers.nesfab]
name = "NESFab LSP"
language = "NESFab"

[grammars.nesfab]
repository = "https://github.com/hnd2/tree-sitter-nesfab"
commit = "f9135244d887e60343e99d87b3069d322c57a526"
