name = "NESFab"
grammer = "nesfab"
path_suffixes = ["fab", "mirofab"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
# autoclose_before = "}])"
# brackets = [
#     { start = "{", end = "}", close = true, newline = true },
#     { start = "[", end = "]", close = true, newline = true },
#     { start = "(", end = ")", close = true, newline = true },
#     { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
# ]
tab_size = 4
